POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Ridge Forrester",
  "ssn": "120666-696X",
  "gender": "male",
  "occupation": "fashion mogul",
  "dateOfBirth": "1966-06-12"
}